[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
